---
- include_tasks: redhat.yml
  when: ansible_os_family == "RedHat"

- include_tasks: ubuntu.yml
  when: ansible_os_family == "Debian"

- name: configure watchdog daemon
  template:
    src: watchdog.conf.j2
    dest: /etc/watchdog.conf
  notify: restart watchdog daemon

- name: Enable watchdog daemon
  service:
    name: "{{ watchdog_service_name }}"
    enabled: yes

